require "core.options"
require "core.remap"
require "plugins.blink-cmp"
require "plugins.bufferline"
require "plugins.mini"
-- Active colorscheme; swap by toggling these requires.
-- require "plugins.colorscheme-tokyonight"
require "plugins.colorscheme-monokai-pro"
require "plugins.gitsigns"
require "plugins.leap"
require "plugins.lsp"
require "plugins.neoscroll"
require "plugins.neotree"
require "plugins.render-markdown"
require "plugins.telescope"
require "plugins.toggleterm"
require "plugins.treesitter"
